# Generated by Django 5.0.1 on 2024-02-06 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('8e641869-84ba-494c-961b-6f725dda15b5'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updtaed_at', models.DateField(auto_now_add=True)),
                ('task_title', models.CharField(max_length=100)),
                ('task_desc', models.CharField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
