# Generated by Django 5.0.1 on 2024-02-06 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_task_created_at_alter_task_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updtaed_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a68fa54e-16eb-48cf-8dc1-3524b67b289b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
