# Generated by Django 5.0.1 on 2024-02-06 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_rename_updtaed_at_task_updated_at_alter_task_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8c54fe7f-b42d-40d7-9a40-2d8e130ae361'), editable=False, primary_key=True, serialize=False),
        ),
    ]
