# Generated by Django 5.0.1 on 2024-02-06 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_alter_task_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3ddf9af9-93c4-4cda-b725-78feb1ef4cc7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TimingTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('3ddf9af9-93c4-4cda-b725-78feb1ef4cc7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('timing', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
