# Generated by Django 5.0.3 on 2024-05-21 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_alter_task_uid_timingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d19f0ba1-4fba-45ab-95f7-75fee5350a9f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timingtask',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d19f0ba1-4fba-45ab-95f7-75fee5350a9f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
