# Generated by Django 5.0 on 2024-05-26 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_product_alter_task_uid_alter_timingtask_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('62b89d3d-570d-499a-b46f-6776a50a9e1b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timingtask',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('62b89d3d-570d-499a-b46f-6776a50a9e1b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
