# Generated by Django 5.0.2 on 2024-06-16 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0008_alter_task_uid_alter_timingtask_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('46c84f73-52fd-4edf-9a2e-810f0d77f6bd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timingtask',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('46c84f73-52fd-4edf-9a2e-810f0d77f6bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
