# Generated by Django 5.0.2 on 2024-06-16 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_alter_task_uid_alter_timingtask_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ee842344-0f93-413d-819e-a72f33e166a6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timingtask',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ee842344-0f93-413d-819e-a72f33e166a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
